apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{- include "gotenberg.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
{{- if .Values.service.nodePort }}
      nodePort: {{- .Values.service.nodePort }}
{{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "gotenberg.selectorLabels" . | nindent 4 }}
